logs/urls.py
# -*- mode: python; coding: utf-8 -*-
# Copyright (C) 2017-2019 by BDE ENS Paris-Saclay
# SPDX-License-Identifier: GPL-3.0-or-later

from django.conf.urls import url

from . import views

app_name = 'logs'
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^stats_actions/$', views.stats_actions, name='stats-actions'),
]

med/urls.py
# -*- mode: python; coding: utf-8 -*-
# Copyright (C) 2017-2019 by BDE ENS Paris-Saclay
# SPDX-License-Identifier: GPL-3.0-or-later

from django.contrib.auth.views import PasswordResetView
from django.urls import include, path
from django.views.generic import RedirectView
from rest_framework import routers

import media.views
import users.views
from .admin import admin_site

# API router
router = routers.DefaultRouter()
router.register(r'authors', media.views.AuthorViewSet)
router.register(r'media/comic', media.views.ComicViewSet)
router.register(r'media/manga', media.views.MangaViewSet)
router.register(r'media/cd', media.views.CDViewSet)
router.register(r'media/vinyl', media.views.VinylViewSet)
router.register(r'media/novel', media.views.NovelViewSet)
router.register(r'media/review', media.views.ReviewViewSet)
router.register(r'media/future', media.views.FutureMediumViewSet)
router.register(r'borrowed_items', media.views.BorrowViewSet)
router.register(r'games', media.views.GameViewSet)
router.register(r'users', users.views.UserViewSet)
router.register(r'groups', users.views.GroupViewSet)

urlpatterns = [
    path('', media.views.IndexView.as_view(), name='index'),

    # Include project routers
    path('users/', include('users.urls')),
    path('media/', include('media.urls')),
    path('logs/', include('logs.urls')),

    # REST API
    path('api/', include(router.urls)),
    path('api-auth/', include('rest_framework.urls')),

    # Include Django Contrib and Core routers
    path('accounts/password_reset/', PasswordResetView.as_view(),
         name='admin_password_reset'),
    path('i18n/', include('django.conf.urls.i18n')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/profile/', RedirectView.as_view(pattern_name='index')),
    path('database/doc/', include('django.contrib.admindocs.urls')),
    path('database/', admin_site.urls),
]

logs/views.py
# -*- mode: python; coding: utf-8 -*-
# Copyright (C) 2017-2019 by BDE ENS Paris-Saclay
# SPDX-License-Identifier: GPL-3.0-or-later

from django.contrib.admin.views.decorators import staff_member_required
from django.contrib.auth.decorators import login_required
from django.core.paginator import EmptyPage, PageNotAnInteger, Paginator
from django.db.models import Count
from django.shortcuts import render
from django.utils.translation import gettext_lazy as _
from reversion.models import Revision
from med.settings import PAGINATION_NUMBER
from users.models import User


@login_required
@staff_member_required
def index(request):
    revisions = Revision.objects.all().order_by(
        'date_created').reverse().select_related('user').prefetch_related(
        'version_set__object')
    paginator = Paginator(revisions, PAGINATION_NUMBER)
    page = request.GET.get('page')
    try:
        revisions = paginator.page(page)
    except PageNotAnInteger:
        # If page is not an integer, deliver first page.
        revisions = paginator.page(1)
    except EmptyPage:
        # If page is out of range (e.g. 9999), deliver last page of results.
        revisions = paginator.page(paginator.num_pages)
    return render(request, 'logs/index.html', {'revisions_list': revisions})


@login_required
@staff_member_required
def stats_actions(request):
    stats = User.objects.annotate(num=Count('revision')).order_by('-num')[:10]
    return render(request, 'logs/stats_users.html', {
        'title': _("Database edits by user"),
        'stats': stats,
    })

logs/templates/logs/aff_actions.html
{% comment %}
SPDX-License-Identifier: GPL-3.0-or-later
{% endcomment %}

{% if revisions_list.paginator %}
    {% include "pagination.html" with list=revisions_list %}
{% endif %}

{% load logs_extra %}

<table class="table table-striped">
    <thead>
    <tr>
        <th>Objet modifié</th>
        <th>Type de l'objet</th>
        <th>Modification par</th>
        <th>Date de modification</th>
        <th>Commentaire</th>
        <th></th>
    </tr>
    </thead>
    {% for revision in revisions_list %}
        {% for reversion in revision.version_set.all %}
            <tr>
                <td>{{ reversion.object|truncatechars:20 }}</td>
                <td>{{ reversion.object|classname }}</td>
                <td>{{ revision.user }}</td>
                <td>{{ revision.date_created }}</td>
                <td>{{ revision.comment }}</td>
            </tr>
        {% endfor %}
    {% endfor %}
</table>

logs/templates/logs/index.html
{% extends "logs/sidebar.html" %}
{% comment %}
SPDX-License-Identifier: GPL-3.0-or-later
{% endcomment %}

{% block title %}Statistiques{% endblock %}

{% block content %}
    <h2>Actions effectuées</h2>
    {% include "logs/aff_actions.html" with  revisions_list=revisions_list %}
{% endblock %}

logs/templates/logs/sidebar.html
{% extends "base.html" %}
{% comment %}
SPDX-License-Identifier: GPL-3.0-or-later
{% endcomment %}

{% block sidebar %}
    <a class="list-group-item list-group-item-info" href="{% url "logs:index" %}">
        <i class="glyphicon glyphicon-stats"></i>
        Évènements
    </a>
    <a class="list-group-item list-group-item-info" href="{% url "logs:stats-actions" %}">
        <i class="glyphicon glyphicon-stats"></i>
        Actions sur la bdd
    </a>
{% endblock %}

logs/templates/logs/stats_users.html
{% extends "logs/sidebar.html" %}
{% comment %}
SPDX-License-Identifier: GPL-3.0-or-later
{% endcomment %}

{% load i18n %}

{% block content %}
    <table class="table">
        <thead>
        <tr>
            <th>{% trans "user"|capfirst %}</th>
            <th>{% trans "Database edits" %}</th>
            <th>{% trans "Rank" %}</th>
        </tr>

        </thead>
        <tbody>
        {% for stat in stats %}
            <tr>
                <td>{{ stat|truncatechars:25 }}</td>
                <td>{{ stat.num }}</td>
                <td>{{ forloop.counter }}</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
{% endblock %}